const currencyResponse = {
  result: "success",
  totalresults: "32",
  currencies: {
    currency: [
      {
        id: "1",
        code: "USD",
        prefix: "$",
        suffix: " USD",
        format: "1",
        rate: "1.00000",
      },
      {
        id: "2",
        code: "EUR",
        prefix: "€",
        suffix: " EUR",
        format: "1",
        rate: "0.91234",
      },
      {
        id: "3",
        code: "GBP",
        prefix: "£",
        suffix: " GBP",
        format: "1",
        rate: "0.78901",
      },
      {
        id: "4",
        code: "JPY",
        prefix: "¥",
        suffix: " JPY",
        format: "1",
        rate: "149.32100",
      },
      {
        id: "5",
        code: "AUD",
        prefix: "A$",
        suffix: " AUD",
        format: "1",
        rate: "1.52340",
      },
      {
        id: "6",
        code: "CAD",
        prefix: "C$",
        suffix: " CAD",
        format: "1",
        rate: "1.34560",
      },
      {
        id: "7",
        code: "CHF",
        prefix: "₣",
        suffix: " CHF",
        format: "1",
        rate: "0.88790",
      },
      {
        id: "8",
        code: "CNY",
        prefix: "¥",
        suffix: " CNY",
        format: "1",
        rate: "7.18900",
      },
      {
        id: "9",
        code: "INR",
        prefix: "₹",
        suffix: " INR",
        format: "1",
        rate: "82.94500",
      },
      {
        id: "10",
        code: "BRL",
        prefix: "R$",
        suffix: " BRL",
        format: "1",
        rate: "4.95670",
      },
      {
        id: "11",
        code: "RUB",
        prefix: "₽",
        suffix: " RUB",
        format: "1",
        rate: "92.34500",
      },
      {
        id: "12",
        code: "KRW",
        prefix: "₩",
        suffix: " KRW",
        format: "1",
        rate: "1334.56700",
      },
      {
        id: "13",
        code: "SGD",
        prefix: "S$",
        suffix: " SGD",
        format: "1",
        rate: "1.34560",
      },
      {
        id: "14",
        code: "NZD",
        prefix: "NZ$",
        suffix: " NZD",
        format: "1",
        rate: "1.65430",
      },
      {
        id: "15",
        code: "MXN",
        prefix: "$",
        suffix: " MXN",
        format: "1",
        rate: "17.12300",
      },
      {
        id: "16",
        code: "HKD",
        prefix: "HK$",
        suffix: " HKD",
        format: "1",
        rate: "7.82340",
      },
      {
        id: "17",
        code: "ZAR",
        prefix: "R",
        suffix: " ZAR",
        format: "1",
        rate: "18.90120",
      },
      {
        id: "18",
        code: "SEK",
        prefix: "kr",
        suffix: " SEK",
        format: "1",
        rate: "10.45670",
      },
      {
        id: "19",
        code: "NOK",
        prefix: "Nkr",
        suffix: " NOK",
        format: "1",
        rate: "10.67890",
      },
      {
        id: "20",
        code: "DKK",
        prefix: "kr",
        suffix: " DKK",
        format: "1",
        rate: "6.89012",
      },
      {
        id: "21",
        code: "PLN",
        prefix: "zł",
        suffix: " PLN",
        format: "1",
        rate: "4.01230",
      },
      {
        id: "22",
        code: "THB",
        prefix: "฿",
        suffix: " THB",
        format: "1",
        rate: "35.67890",
      },
      {
        id: "23",
        code: "AED",
        prefix: "د.إ",
        suffix: " AED",
        format: "1",
        rate: "3.67250",
      },
      {
        id: "24",
        code: "SAR",
        prefix: "﷼",
        suffix: " SAR",
        format: "1",
        rate: "3.75000",
      },
      {
        id: "25",
        code: "MYR",
        prefix: "RM",
        suffix: " MYR",
        format: "1",
        rate: "4.72340",
      },
      {
        id: "26",
        code: "IDR",
        prefix: "Rp",
        suffix: " IDR",
        format: "1",
        rate: "15678.90000",
      },
      {
        id: "27",
        code: "PHP",
        prefix: "₱",
        suffix: " PHP",
        format: "1",
        rate: "56.78900",
      },
      {
        id: "28",
        code: "TWD",
        prefix: "NT$",
        suffix: " TWD",
        format: "1",
        rate: "31.45670",
      },
      {
        id: "29",
        code: "TRY",
        prefix: "₺",
        suffix: " TRY",
        format: "1",
        rate: "30.12340",
      },
      {
        id: "30",
        code: "ILS",
        prefix: "₪",
        suffix: " ILS",
        format: "1",
        rate: "3.67890",
      },
      {
        id: "31",
        code: "CZK",
        prefix: "Kč",
        suffix: " CZK",
        format: "1",
        rate: "22.89012",
      },
      {
        id: "32",
        code: "HUF",
        prefix: "Ft",
        suffix: " HUF",
        format: "1",
        rate: "356.78900",
      },
    ],
  },
};

export default currencyResponse;
